
name: Running test pipeline from github version

on:

  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
            pip install codecov pytest pytest-cov
            pip install -e .
            pip install flake8
            sudo apt-get install graphviz libgraphviz-dev
            pip install --upgrade pygraphviz graphviz

      - name: Test with pytest
        run:
            py.test --cov macapype --ignore=examples/ --ignore=run_examples/

      - name: Flake8
        run:
            flake8 --count macapype
            

      - name: Running test pipeline
        run:
            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/ -out /home/runner/work/macapype/macapype/resulsts -soft ANTS_test -species macaque 
