
name: Running test pipeline from github version

on:

  push:
    branches:
      - test_swap


jobs:
  run-test:
    name: Test one pipeline in macapype_CI.zip
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |
            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

      - name: Set up swap space
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c
        with:
          swap-size-gb: 10


      - name: Running all test pipelines
        run: |
            pwd
            echo ""
            ls macapype_CI
            echo ""
            ls macapype_CI/macaque_prime-de
            echo ""

            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/marmo-marmobrain -out /data/marmo-marmobrain/results -soft ANTS -species marmo -indiv /data/marmo-marmobrain/indiv_params_segment_marmo.json -sub 8034 -ses 01 -deriv
